#### Numpy:
### Numpy:numerical python
### Numpy is a library in python which is used to build different dimensional arrays

In [1]:

import numpy as np
a=[1,2,3,4]
a

[1, 2, 3, 4]

In [2]:

d=np.array(a)
print(d)
d

[1 2 3 4]


array([1, 2, 3, 4])

In [3]:
d1=np.array([[1,2,3,4],[5,6,7,8]])

In [4]:
d1.shape


(2, 4)

In [5]:
d2=np.arange(1,101)
d2.reshape(10,10)


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [6]:
 np.linspace(0,8,10)

array([0.        , 0.88888889, 1.77777778, 2.66666667, 3.55555556,
       4.44444444, 5.33333333, 6.22222222, 7.11111111, 8.        ])

In [7]:
np.random.randint(0,20,size=(2,4))


array([[18, 13,  7, 12],
       [14,  4,  3, 13]])

In [8]:
np.random.randint(0,20)


9

In [9]:
np.ones((4,3),int)


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [10]:
n=np.zeros((4,3),int)


In [11]:
np.vstack([n,n*2])


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [12]:
np.hstack([n,n*2])


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [13]:
n1=np.array([1,2,3,4])
n2=np.array([5,6,7,8])
n1,n2

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [14]:
n1+n2


array([ 6,  8, 10, 12])

In [15]:
n1-n2


array([-4, -4, -4, -4])

In [16]:
n2-n1


array([4, 4, 4, 4])

In [17]:
n2*n1


array([ 5, 12, 21, 32])

In [18]:
n2/n1


array([5.        , 3.        , 2.33333333, 2.        ])

In [19]:
n2**n1


array([   5,   36,  343, 4096], dtype=int32)

In [20]:
n2%n1


array([0, 0, 1, 0], dtype=int32)

In [21]:
n1.dot(n2)###dot product


70

In [22]:
d1


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
d1.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [26]:
d1.max()


8

In [27]:
d1.min()


1

In [28]:
d1.mean()


4.5